version: "3"
services:
    express:
        image: docker.pkg.github.com/unclesamswiss/iobroker-dev-portal/express:main
        restart: always
        depends_on:
            - mongo
        environment:
            TEMP_DIR: /tmp
            GOOGLE_APPLICATION_CREDENTIALS: /app/google-translate-credentials.json
    mongo:
        image: "mongo:4.4"
        restart: always
        volumes:
            - mongo-data:/data/db
volumes:
    mongo-data: {}
