name: Publish Docker Image

on:
  push:
    branches:
      - "main"
    pull_request: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: UncleSamSwiss/iobroker-dev-portal/express
          path: ./express
          tag_with_ref: true
          tag_with_sha: true
